export interface Artwork {
  id: string;
  title: string;
  titleJa: string;
  description: string;
  descriptionJa: string;
  difficulty: 'easy' | 'medium' | 'hard';
  tags: string[];
}

export const artworks: Artwork[] = [
  {
    id: 'flow-fields',
    title: 'Flow Fields',
    titleJa: 'フローフィールド',
    description: 'Thousands of particles flow through an invisible vector field, creating organic, painterly trails reminiscent of Van Gogh\'s brushwork.',
    descriptionJa: '画面全体に目に見えない「風の流れ」のようなベクトル場を作り、その上を数千個の粒子が移動して軌跡を描くアートです。',
    difficulty: 'easy',
    tags: ['Perlin Noise', 'Particles', 'Organic'],
  },
  {
    id: 'physarum',
    title: 'Physarum Simulation',
    titleJa: 'フィザラム・シミュレーション（粘菌）',
    description: 'Simulating the behavior of slime mold (Physarum polycephalum) as it creates efficient networks, resembling blood vessels or city roads.',
    descriptionJa: '単細胞生物である「粘菌」が餌を求めてネットワークを作る様子を模倣したアルゴリズムです。',
    difficulty: 'hard',
    tags: ['Agent-based', 'Pixel Manipulation', 'Biology'],
  },
  {
    id: 'reaction-diffusion',
    title: 'Reaction-Diffusion',
    titleJa: '反応拡散系',
    description: 'Simulating two chemicals reacting and diffusing (Gray-Scott model), creating patterns seen in zebra stripes, coral, and fingerprints.',
    descriptionJa: '2つの化学物質が反応し合いながら拡散していく様子をシミュレーションします（グレイ・スコット・モデル）。',
    difficulty: 'hard',
    tags: ['Cellular Automata', 'Convolution', 'Mathematics'],
  },
  {
    id: 'strange-attractors',
    title: 'Strange Attractors',
    titleJa: 'ストレンジ・アトラクタ',
    description: 'Visualizing chaotic systems through mathematical equations, revealing butterfly-like structures in 3D space (Lorenz Attractor).',
    descriptionJa: 'カオス理論に基づいた数式を用いて、3次元空間に点を打ち続けることで現れる奇妙な軌道を描画します。',
    difficulty: 'medium',
    tags: ['WEBGL', 'Differential Equations', '3D'],
  },
  {
    id: 'recursive-subdivision',
    title: 'Recursive Subdivision',
    titleJa: '再帰的な分割',
    description: 'Randomly dividing the canvas recursively, creating geometric patterns similar to Mondrian paintings or aerial city views.',
    descriptionJa: '画面をランダムに分割し、分割されたエリアをさらに分割…と繰り返す手法です。',
    difficulty: 'easy',
    tags: ['Recursion', 'Geometry', 'Mondrian'],
  },
  {
    id: 'circle-packing',
    title: 'Circle Packing',
    titleJa: 'サークル・パッキング',
    description: 'Filling space with non-overlapping circles that grow until they touch, creating organic cell-like or bubble patterns.',
    descriptionJa: '円同士が重ならないように、空間が埋まるまで新しい円を配置・成長させ続ける手法です。',
    difficulty: 'medium',
    tags: ['Collision Detection', 'Optimization', 'Organic'],
  },
  {
    id: 'kinetic-typography',
    title: 'Kinetic Typography',
    titleJa: 'キネティック・タイポグラフィ',
    description: 'Interactive text where letter particles react to mouse movement, scattering and reforming dynamically.',
    descriptionJa: '文字を構成する点をパーティクルとして扱い、マウスの動きに反応して弾け飛んだり、元に戻ったりするインタラクティブな文字表現です。',
    difficulty: 'medium',
    tags: ['Typography', 'Physics', 'Interactive'],
  },
  {
    id: 'audio-reactive',
    title: 'Audio Reactive',
    titleJa: 'オーディオ・リアクティブ',
    description: 'Visualizing microphone input or music through pulsating shapes and waveforms that respond to sound frequencies.',
    descriptionJa: 'マイク入力や音楽ファイルの波形・周波数を解析し、ビジュアルに変換します。',
    difficulty: 'medium',
    tags: ['FFT', 'Audio', 'Polar Coordinates'],
  },
  {
    id: 'shader-art',
    title: 'Shader Art',
    titleJa: 'シェーダーアート',
    description: 'Using GLSL shaders for GPU-accelerated effects, enabling fluid simulations and raymarching at high performance.',
    descriptionJa: 'p5.js上でGLSL（シェーダー言語）を動かします。',
    difficulty: 'hard',
    tags: ['GLSL', 'GPU', 'Fragment Shader'],
  },
  {
    id: 'vector-morphing',
    title: 'Vector Morphing',
    titleJa: 'ベクトル・モーフィング',
    description: 'Smoothly transitioning between different shapes by interpolating vertex positions, creating mesmerizing transformations.',
    descriptionJa: 'ある図形から別の図形へ、頂点の座標をスムーズに移動させて変形させます。',
    difficulty: 'easy',
    tags: ['Lerp', 'Animation', 'Shapes'],
  },
  {
    id: 'constellation',
    title: 'Constellation',
    titleJa: 'コンステレーション（星座）',
    description: 'Floating particles connected by lines when close, creating a network effect. Mouse interaction repels particles, ideal for tech company backgrounds.',
    descriptionJa: '浮遊する点が一定距離に近づいたときだけ線で結ばれる表現です。マウスの近くにある点は反発し、インタラクティブ性の高い背景に最適です。',
    difficulty: 'easy',
    tags: ['Network', 'Particles', 'Interactive', 'Web Background'],
  },
  {
    id: 'voronoi',
    title: 'Voronoi Diagram',
    titleJa: 'ボロノイ図',
    description: 'A geometric pattern that divides the screen into cell-like regions. The boundaries organically shift as the mouse moves, creating a modern, intellectual impression.',
    descriptionJa: '画面を細胞のように分割する幾何学模様です。マウスの移動に合わせて境界線が有機的に変化し、モダンで知的な印象を与えます。',
    difficulty: 'medium',
    tags: ['Geometry', 'Cellular', 'Interactive', 'Web Background'],
  },
  {
    id: 'wireframe-terrain',
    title: '3D Wireframe Terrain',
    titleJa: '3Dワイヤーフレーム・テレイン',
    description: 'A retro-futuristic terrain mesh flowing infinitely using Perlin noise. Mouse controls the viewing angle and speed, creating an immersive experience.',
    descriptionJa: 'グリッド状の地形が無限に流れていくレトロフューチャーな表現です。パーリンノイズによる高さ制御とWEBGLで没入感のある背景を作ります。',
    difficulty: 'medium',
    tags: ['WEBGL', '3D', 'Perlin Noise', 'Retro'],
  },
  {
    id: 'magnetic-grid',
    title: 'Magnetic Grid',
    titleJa: 'マグネティック・グリッド',
    description: 'Short lines arranged in a grid all pointing toward the mouse cursor, creating a strong sense of user control with lightweight performance.',
    descriptionJa: '画面全体にグリッド状に配置された短い線（針）が、すべてマウスカーソルの方向を向く表現です。シンプルで動作も軽快です。',
    difficulty: 'easy',
    tags: ['Grid', 'Interactive', 'Trigonometry', 'Web Background'],
  },
  {
    id: 'liquid-blobs',
    title: 'Liquid Blobs',
    titleJa: 'リキッド・ブロブ',
    description: 'Amoeba-like shapes floating and morphing organically, creating a soft, approachable impression. Perfect for creative and startup websites.',
    descriptionJa: 'アメーバのような不定形の物体がゆったりと形を変えながら浮遊します。柔らかさと親しみやすさを演出します。',
    difficulty: 'medium',
    tags: ['Organic', 'Noise', 'Blobs', 'Web Background'],
  },
  {
    id: 'ascii-rain',
    title: 'ASCII Art Rain',
    titleJa: 'ASCIIアート・レイン',
    description: 'Matrix-inspired falling characters creating a cyberpunk atmosphere. Mouse proximity highlights nearby characters with a different color.',
    descriptionJa: '文字が雨のように降り注ぐマトリックス風の表現です。マウス周辺の文字がハイライトされ、サイバーパンクな雰囲気を演出します。',
    difficulty: 'easy',
    tags: ['Typography', 'Matrix', 'Cyberpunk', 'Web Background'],
  },
  {
    id: 'cursor-trail',
    title: 'Cursor Trail Effect',
    titleJa: 'カーソル・トレイル・エフェクト',
    description: 'Geometric shapes follow the mouse cursor with physics-based movement, fading away over time. Click to create an explosive burst effect.',
    descriptionJa: 'マウスカーソルの動きに合わせて幾何学的な図形が追従して消えていくエフェクトです。クリックで弾ける演出も加えています。',
    difficulty: 'easy',
    tags: ['Particles', 'Physics', 'Interactive', 'Web Background'],
  },
  {
    id: 'parallax-particles',
    title: 'Parallax Particles',
    titleJa: 'パララックス・パーティクル',
    description: 'Particles of varying sizes move at different speeds based on their depth, creating a pseudo-3D parallax effect as the mouse moves.',
    descriptionJa: '大きさの異なる図形をマウス位置に応じて異なる速度で動かし、2D画面に擬似的な3D奥行きを与えます。',
    difficulty: 'easy',
    tags: ['Parallax', 'Depth', '3D Effect', 'Web Background'],
  },
  {
    id: 'geometric-wave',
    title: 'Geometric Wave',
    titleJa: '幾何学的ウェーブ',
    description: 'Aligned squares and shapes ripple with wave-like rotation and size changes. Creates orderly beauty suitable for architectural and structural designs.',
    descriptionJa: '正方形や線が整列し、波打つように回転したりサイズが変わったりします。整然とした美しさがあり、建築やインテリア系サイトに最適です。',
    difficulty: 'medium',
    tags: ['Geometry', 'Waves', 'Sin/Cos', 'Web Background'],
  },
  {
    id: 'glitch-effect',
    title: 'Glitch Effect',
    titleJa: 'グリッチ・エフェクト',
    description: 'Digital noise and chromatic aberration effects that trigger randomly and on mouse proximity, creating an underground, cutting-edge aesthetic.',
    descriptionJa: '背景が時折デジタルノイズや色収差を起こして乱れます。バグやアンダーグラウンドな印象を与え、ファッションや音楽系サイトに適しています。',
    difficulty: 'hard',
    tags: ['Glitch', 'Chromatic Aberration', 'Cyberpunk', 'Web Background'],
  },
  // Mathematical Generative Art
  {
    id: 'superformula',
    title: 'Superformula',
    titleJa: 'スーパーフォーミュラ',
    description: 'A single polar equation that can describe countless natural shapes - flowers, starfish, crystals, and more. Move the mouse to morph the shape in real-time.',
    descriptionJa: '円や楕円の方程式を一般化した極座標方程式で、花・ヒトデ・結晶など自然界の多様な形状を描きます。マウス位置でリアルタイムに形が変形します。',
    difficulty: 'medium',
    tags: ['Mathematics', 'Polar Coordinates', 'Nature', 'Interactive'],
  },
  {
    id: 'fourier-series',
    title: 'Fourier Series Visualization',
    titleJa: 'フーリエ級数の可視化',
    description: 'Any complex closed curve can be drawn using rotating circles (epicycles). Watch as the Fourier transform reconstructs shapes from harmonic components.',
    descriptionJa: '「どんな複雑な閉曲線も回転する円の和で表現できる」というフーリエ級数の数学的特性を可視化。複数の円が連結して回転し線を描きます。',
    difficulty: 'hard',
    tags: ['Fourier Transform', 'Epicycles', 'Mathematics', 'Animation'],
  },
  {
    id: 'phyllotaxis',
    title: 'Fibonacci Phyllotaxis',
    titleJa: 'フィボナッチ・フィロタキシス',
    description: 'The golden angle (137.5°) arrangement found in sunflowers and pinecones. A simple yet profound demonstration of mathematical beauty in nature.',
    descriptionJa: 'ヒマワリの種や松ぼっくりの配列に見られる黄金角を利用した配置パターン。シンプルながら自然界の数学的美しさを表現します。',
    difficulty: 'easy',
    tags: ['Golden Ratio', 'Fibonacci', 'Nature', 'Patterns'],
  },
  {
    id: 'de-jong-attractor',
    title: 'De Jong Attractor',
    titleJa: 'デ・ヨング・アトラクタ',
    description: 'A chaotic dynamical system that creates intricate, fabric-like patterns through millions of iterations. Press 1-6 for presets or click to explore.',
    descriptionJa: 'カオス理論に基づく写像で、何百万回もの計算により布のような不思議なテクスチャが現れます。プリセットで様々なパターンを探索できます。',
    difficulty: 'hard',
    tags: ['Chaos Theory', 'Attractors', 'Density Mapping', 'Mathematics'],
  },
  {
    id: 'maurer-rose',
    title: 'Maurer Rose',
    titleJa: 'モーラー・ローズ',
    description: 'Connecting points on a rose curve at specific angular intervals creates stunning wire-frame structures. Move mouse to change petal count and step angle.',
    descriptionJa: 'バラ曲線上の点を特定のステップ角度で線で結び、金属的なワイヤーフレームのような幾何学模様を生成します。',
    difficulty: 'medium',
    tags: ['Rose Curve', 'Geometry', 'Trigonometry', 'Interactive'],
  },
  {
    id: 'voronoi-delaunay',
    title: 'Voronoi & Delaunay',
    titleJa: 'ボロノイ図とドロネー三角形分割',
    description: 'Space partitioning based on distance to seed points. Voronoi creates cell-like regions while Delaunay connects points in optimal triangles.',
    descriptionJa: '母点との距離に基づいて空間を分割するアルゴリズム。細胞分裂のような領域変化とステンドグラス風の美しさを表現します。',
    difficulty: 'medium',
    tags: ['Voronoi', 'Delaunay', 'Computational Geometry', 'Interactive'],
  },
  {
    id: 'complex-domain-coloring',
    title: 'Complex Domain Coloring',
    titleJa: '複素関数ドメインカラーリング',
    description: 'Visualizing complex mathematical functions f(z) using color. The argument maps to hue, magnitude to brightness, revealing hidden fractal structures.',
    descriptionJa: '複素平面上の関数を色で可視化。偏角を色相、絶対値を明度に割り当て、フラクタル的でサイケデリックな無限の模様を描きます。',
    difficulty: 'hard',
    tags: ['Complex Analysis', 'Domain Coloring', 'Fractals', 'Mathematics'],
  },
  {
    id: 'chladni-patterns',
    title: 'Chladni Patterns',
    titleJa: 'クラドニ図形',
    description: 'Simulating the geometric patterns formed on vibrating plates. Particles gather at nodal lines where amplitude is zero, like sand on a resonating surface.',
    descriptionJa: '振動する板の上に現れる幾何学模様（定在波の節）をシミュレーション。パーティクルがZ=0の場所に集まり、砂の実験を再現します。',
    difficulty: 'medium',
    tags: ['Wave Equation', 'Physics', 'Particles', 'Acoustics'],
  },
  {
    id: 'apollonian-gasket',
    title: 'Apollonian Gasket',
    titleJa: 'アポロニウスのギャスケット',
    description: 'A fractal created by recursively filling tangent circles using Descartes Circle Theorem. Watch as mathematically perfect circles fill the space infinitely.',
    descriptionJa: '円反転操作を繰り返すことで、円の中に円が無限に敷き詰められるフラクタル図形。デカルトの円定理に基づく完璧な美しさです。',
    difficulty: 'hard',
    tags: ['Fractals', 'Circle Inversion', 'Recursion', 'Descartes Theorem'],
  },
  {
    id: 'marching-squares',
    title: 'Marching Squares',
    titleJa: 'マーチング・スクエア',
    description: 'An algorithm generating contour lines from scalar fields. 3D Perlin noise creates organic topographic patterns like terrain maps or MRI scans.',
    descriptionJa: 'スカラー場から等高線を生成するアルゴリズム。3Dパーリンノイズを断面でスライスし、地形図やMRIスキャンのような有機的模様を動的に生成します。',
    difficulty: 'medium',
    tags: ['Isosurfaces', 'Perlin Noise', 'Contour Lines', 'Algorithm'],
  },
  // Nature of Code inspired generative art
  {
    id: 'levy-flight',
    title: 'Levy Flight',
    titleJa: 'レヴィ・フライト',
    description: 'Random walkers that occasionally take long-distance jumps, creating complex network structures resembling lightning, mold, or neural pathways.',
    descriptionJa: '時折長距離をジャンプするランダム・ウォーカー。自然界の確率分布（べき乗則）に従い、カビや稲妻のような複雑なネットワーク構造を描きます。',
    difficulty: 'medium',
    tags: ['Probability', 'Random Walk', 'Power Law', 'Nature of Code'],
  },
  {
    id: 'gravitational-attractor',
    title: 'Gravitational Attractor',
    titleJa: '重力アトラクター',
    description: 'Particles orbiting invisible gravity points, creating cosmic spirograph patterns through Newton\'s law of universal gravitation.',
    descriptionJa: '見えない重力点の周りを粒子が周回し、ニュートンの万有引力の法則に従って宇宙的なスピログラフのような幾何学模様を生成します。',
    difficulty: 'medium',
    tags: ['Physics', 'Gravity', 'Particles', 'Nature of Code'],
  },
  {
    id: 'double-pendulum',
    title: 'Double Pendulum',
    titleJa: '二重振り子',
    description: 'A chaotic system where two pendulums connected in series create unpredictable, beautiful trajectories. Small initial differences lead to vastly different paths.',
    descriptionJa: '2つの振り子を直列に接続したカオス系。物理法則に従いながら予測不能な軌跡を描き、絵の具を垂らしたような美しいパターンを生成します。',
    difficulty: 'hard',
    tags: ['Chaos', 'Physics', 'Pendulum', 'Nature of Code'],
  },
  {
    id: 'particle-painting',
    title: 'Particle Painting',
    titleJa: 'パーティクル・ペインティング',
    description: 'Interactive particle system where mouse movements create fire, smoke, and magical effects. Each particle has a lifespan, fading organically over time.',
    descriptionJa: 'マウスの動きに合わせて火花や煙のような粒子を発生させるインタラクティブなシステム。各粒子に寿命を設定し、自然に消えていきます。',
    difficulty: 'easy',
    tags: ['Particles', 'Lifespan', 'Interactive', 'Nature of Code'],
  },
  {
    id: 'autonomous-agents',
    title: 'Autonomous Agents',
    titleJa: '自律エージェント',
    description: 'Agents with simple desires - seek targets, flee from mouse, avoid each other. These steering behaviors create emergent flock-like movement patterns.',
    descriptionJa: '「目標を追う」「マウスから逃げる」といった単純な欲求を持つエージェント群。ステアリング力により、魚や羊の群れのような有機的な動きが創発します。',
    difficulty: 'medium',
    tags: ['Steering', 'Seek', 'Flee', 'Nature of Code'],
  },
  {
    id: 'flocking',
    title: 'Flocking Simulation',
    titleJa: 'フロッキング・シミュレーション',
    description: 'Reynolds\' Boids algorithm simulating bird flocks. Three simple rules - separation, alignment, cohesion - create remarkably realistic swarm behavior.',
    descriptionJa: 'レイノルズの「Boids」アルゴリズムによる鳥の群れシミュレーション。分離・整列・結合の3つのルールだけで驚くほどリアルな群れの動きを再現します。',
    difficulty: 'medium',
    tags: ['Boids', 'Flocking', 'Emergence', 'Nature of Code'],
  },
  {
    id: 'cellular-automata',
    title: 'Cellular Automata',
    titleJa: 'セル・オートマトン',
    description: 'Wolfram\'s elementary cellular automata generating complex patterns from simple rules. Rule 30 creates patterns found in seashells and ancient textiles.',
    descriptionJa: 'ウルフラムの一次元セル・オートマトン。単純なルール（例：ルール30）から、貝殻の模様や古代のテキスタイルのような複雑で美しいパターンを生成します。',
    difficulty: 'easy',
    tags: ['Cellular Automata', 'Wolfram', 'Emergence', 'Nature of Code'],
  },
  {
    id: 'fractal-tree',
    title: 'Fractal Tree',
    titleJa: 'フラクタル樹木',
    description: 'Recursive branching creates organic tree structures. Wind simulation via mouse position adds life, while randomness produces unique natural forms.',
    descriptionJa: '再帰的な枝分かれで有機的な木を描画。マウス位置で風を加え、枝の角度を揺らすことで本物の盆栽や神経系のような構造が生まれます。',
    difficulty: 'medium',
    tags: ['Recursion', 'Fractals', 'L-System', 'Nature of Code'],
  },
  {
    id: 'genetic-algorithm',
    title: 'Evolving Designs',
    titleJa: '進化するデザイン',
    description: 'Interactive evolution of abstract art using genetic algorithms. Select your favorites to breed the next generation through crossover and mutation.',
    descriptionJa: '遺伝的アルゴリズムによるインタラクティブな進化。気に入った個体を選択すると、交叉・突然変異を経て次世代が誕生し、好みの抽象画に進化させられます。',
    difficulty: 'medium',
    tags: ['Genetic Algorithm', 'Evolution', 'Interactive', 'Nature of Code'],
  },
  {
    id: 'neural-creatures',
    title: 'Neural Creatures',
    titleJa: 'ニューロ・クリーチャー',
    description: 'Creatures with simple neural network brains learn to navigate around obstacles. Watch evolution in action as generations become smarter at reaching goals.',
    descriptionJa: '単純なニューラルネットワークを脳に持つ生き物が障害物を避けることを学習。世代を重ねるごとに賢くなり、目標に到達できるようになる進化の過程を可視化します。',
    difficulty: 'hard',
    tags: ['Neural Network', 'Evolution', 'Learning', 'Nature of Code'],
  },
];

export function getArtwork(id: string): Artwork | undefined {
  return artworks.find(art => art.id === id);
}
