export interface Artwork {
  id: string;
  title: string;
  titleJa: string;
  description: string;
  descriptionJa: string;
  difficulty: 'easy' | 'medium' | 'hard';
  tags: string[];
}

export const artworks: Artwork[] = [
  {
    id: 'flow-fields',
    title: 'Flow Fields',
    titleJa: 'フローフィールド',
    description: 'Thousands of particles flow through an invisible vector field, creating organic, painterly trails reminiscent of Van Gogh\'s brushwork.',
    descriptionJa: '画面全体に目に見えない「風の流れ」のようなベクトル場を作り、その上を数千個の粒子が移動して軌跡を描くアートです。',
    difficulty: 'easy',
    tags: ['Perlin Noise', 'Particles', 'Organic'],
  },
  {
    id: 'physarum',
    title: 'Physarum Simulation',
    titleJa: 'フィザラム・シミュレーション（粘菌）',
    description: 'Simulating the behavior of slime mold (Physarum polycephalum) as it creates efficient networks, resembling blood vessels or city roads.',
    descriptionJa: '単細胞生物である「粘菌」が餌を求めてネットワークを作る様子を模倣したアルゴリズムです。',
    difficulty: 'hard',
    tags: ['Agent-based', 'Pixel Manipulation', 'Biology'],
  },
  {
    id: 'reaction-diffusion',
    title: 'Reaction-Diffusion',
    titleJa: '反応拡散系',
    description: 'Simulating two chemicals reacting and diffusing (Gray-Scott model), creating patterns seen in zebra stripes, coral, and fingerprints.',
    descriptionJa: '2つの化学物質が反応し合いながら拡散していく様子をシミュレーションします（グレイ・スコット・モデル）。',
    difficulty: 'hard',
    tags: ['Cellular Automata', 'Convolution', 'Mathematics'],
  },
  {
    id: 'strange-attractors',
    title: 'Strange Attractors',
    titleJa: 'ストレンジ・アトラクタ',
    description: 'Visualizing chaotic systems through mathematical equations, revealing butterfly-like structures in 3D space (Lorenz Attractor).',
    descriptionJa: 'カオス理論に基づいた数式を用いて、3次元空間に点を打ち続けることで現れる奇妙な軌道を描画します。',
    difficulty: 'medium',
    tags: ['WEBGL', 'Differential Equations', '3D'],
  },
  {
    id: 'recursive-subdivision',
    title: 'Recursive Subdivision',
    titleJa: '再帰的な分割',
    description: 'Randomly dividing the canvas recursively, creating geometric patterns similar to Mondrian paintings or aerial city views.',
    descriptionJa: '画面をランダムに分割し、分割されたエリアをさらに分割…と繰り返す手法です。',
    difficulty: 'easy',
    tags: ['Recursion', 'Geometry', 'Mondrian'],
  },
  {
    id: 'circle-packing',
    title: 'Circle Packing',
    titleJa: 'サークル・パッキング',
    description: 'Filling space with non-overlapping circles that grow until they touch, creating organic cell-like or bubble patterns.',
    descriptionJa: '円同士が重ならないように、空間が埋まるまで新しい円を配置・成長させ続ける手法です。',
    difficulty: 'medium',
    tags: ['Collision Detection', 'Optimization', 'Organic'],
  },
  {
    id: 'kinetic-typography',
    title: 'Kinetic Typography',
    titleJa: 'キネティック・タイポグラフィ',
    description: 'Interactive text where letter particles react to mouse movement, scattering and reforming dynamically.',
    descriptionJa: '文字を構成する点をパーティクルとして扱い、マウスの動きに反応して弾け飛んだり、元に戻ったりするインタラクティブな文字表現です。',
    difficulty: 'medium',
    tags: ['Typography', 'Physics', 'Interactive'],
  },
  {
    id: 'audio-reactive',
    title: 'Audio Reactive',
    titleJa: 'オーディオ・リアクティブ',
    description: 'Visualizing microphone input or music through pulsating shapes and waveforms that respond to sound frequencies.',
    descriptionJa: 'マイク入力や音楽ファイルの波形・周波数を解析し、ビジュアルに変換します。',
    difficulty: 'medium',
    tags: ['FFT', 'Audio', 'Polar Coordinates'],
  },
  {
    id: 'shader-art',
    title: 'Shader Art',
    titleJa: 'シェーダーアート',
    description: 'Using GLSL shaders for GPU-accelerated effects, enabling fluid simulations and raymarching at high performance.',
    descriptionJa: 'p5.js上でGLSL（シェーダー言語）を動かします。',
    difficulty: 'hard',
    tags: ['GLSL', 'GPU', 'Fragment Shader'],
  },
  {
    id: 'vector-morphing',
    title: 'Vector Morphing',
    titleJa: 'ベクトル・モーフィング',
    description: 'Smoothly transitioning between different shapes by interpolating vertex positions, creating mesmerizing transformations.',
    descriptionJa: 'ある図形から別の図形へ、頂点の座標をスムーズに移動させて変形させます。',
    difficulty: 'easy',
    tags: ['Lerp', 'Animation', 'Shapes'],
  },
  {
    id: 'constellation',
    title: 'Constellation',
    titleJa: 'コンステレーション（星座）',
    description: 'Floating particles connected by lines when close, creating a network effect. Mouse interaction repels particles, ideal for tech company backgrounds.',
    descriptionJa: '浮遊する点が一定距離に近づいたときだけ線で結ばれる表現です。マウスの近くにある点は反発し、インタラクティブ性の高い背景に最適です。',
    difficulty: 'easy',
    tags: ['Network', 'Particles', 'Interactive', 'Web Background'],
  },
  {
    id: 'voronoi',
    title: 'Voronoi Diagram',
    titleJa: 'ボロノイ図',
    description: 'A geometric pattern that divides the screen into cell-like regions. The boundaries organically shift as the mouse moves, creating a modern, intellectual impression.',
    descriptionJa: '画面を細胞のように分割する幾何学模様です。マウスの移動に合わせて境界線が有機的に変化し、モダンで知的な印象を与えます。',
    difficulty: 'medium',
    tags: ['Geometry', 'Cellular', 'Interactive', 'Web Background'],
  },
  {
    id: 'wireframe-terrain',
    title: '3D Wireframe Terrain',
    titleJa: '3Dワイヤーフレーム・テレイン',
    description: 'A retro-futuristic terrain mesh flowing infinitely using Perlin noise. Mouse controls the viewing angle and speed, creating an immersive experience.',
    descriptionJa: 'グリッド状の地形が無限に流れていくレトロフューチャーな表現です。パーリンノイズによる高さ制御とWEBGLで没入感のある背景を作ります。',
    difficulty: 'medium',
    tags: ['WEBGL', '3D', 'Perlin Noise', 'Retro'],
  },
  {
    id: 'magnetic-grid',
    title: 'Magnetic Grid',
    titleJa: 'マグネティック・グリッド',
    description: 'Short lines arranged in a grid all pointing toward the mouse cursor, creating a strong sense of user control with lightweight performance.',
    descriptionJa: '画面全体にグリッド状に配置された短い線（針）が、すべてマウスカーソルの方向を向く表現です。シンプルで動作も軽快です。',
    difficulty: 'easy',
    tags: ['Grid', 'Interactive', 'Trigonometry', 'Web Background'],
  },
  {
    id: 'liquid-blobs',
    title: 'Liquid Blobs',
    titleJa: 'リキッド・ブロブ',
    description: 'Amoeba-like shapes floating and morphing organically, creating a soft, approachable impression. Perfect for creative and startup websites.',
    descriptionJa: 'アメーバのような不定形の物体がゆったりと形を変えながら浮遊します。柔らかさと親しみやすさを演出します。',
    difficulty: 'medium',
    tags: ['Organic', 'Noise', 'Blobs', 'Web Background'],
  },
  {
    id: 'ascii-rain',
    title: 'ASCII Art Rain',
    titleJa: 'ASCIIアート・レイン',
    description: 'Matrix-inspired falling characters creating a cyberpunk atmosphere. Mouse proximity highlights nearby characters with a different color.',
    descriptionJa: '文字が雨のように降り注ぐマトリックス風の表現です。マウス周辺の文字がハイライトされ、サイバーパンクな雰囲気を演出します。',
    difficulty: 'easy',
    tags: ['Typography', 'Matrix', 'Cyberpunk', 'Web Background'],
  },
  {
    id: 'cursor-trail',
    title: 'Cursor Trail Effect',
    titleJa: 'カーソル・トレイル・エフェクト',
    description: 'Geometric shapes follow the mouse cursor with physics-based movement, fading away over time. Click to create an explosive burst effect.',
    descriptionJa: 'マウスカーソルの動きに合わせて幾何学的な図形が追従して消えていくエフェクトです。クリックで弾ける演出も加えています。',
    difficulty: 'easy',
    tags: ['Particles', 'Physics', 'Interactive', 'Web Background'],
  },
  {
    id: 'parallax-particles',
    title: 'Parallax Particles',
    titleJa: 'パララックス・パーティクル',
    description: 'Particles of varying sizes move at different speeds based on their depth, creating a pseudo-3D parallax effect as the mouse moves.',
    descriptionJa: '大きさの異なる図形をマウス位置に応じて異なる速度で動かし、2D画面に擬似的な3D奥行きを与えます。',
    difficulty: 'easy',
    tags: ['Parallax', 'Depth', '3D Effect', 'Web Background'],
  },
  {
    id: 'geometric-wave',
    title: 'Geometric Wave',
    titleJa: '幾何学的ウェーブ',
    description: 'Aligned squares and shapes ripple with wave-like rotation and size changes. Creates orderly beauty suitable for architectural and structural designs.',
    descriptionJa: '正方形や線が整列し、波打つように回転したりサイズが変わったりします。整然とした美しさがあり、建築やインテリア系サイトに最適です。',
    difficulty: 'medium',
    tags: ['Geometry', 'Waves', 'Sin/Cos', 'Web Background'],
  },
  {
    id: 'glitch-effect',
    title: 'Glitch Effect',
    titleJa: 'グリッチ・エフェクト',
    description: 'Digital noise and chromatic aberration effects that trigger randomly and on mouse proximity, creating an underground, cutting-edge aesthetic.',
    descriptionJa: '背景が時折デジタルノイズや色収差を起こして乱れます。バグやアンダーグラウンドな印象を与え、ファッションや音楽系サイトに適しています。',
    difficulty: 'hard',
    tags: ['Glitch', 'Chromatic Aberration', 'Cyberpunk', 'Web Background'],
  },
];

export function getArtwork(id: string): Artwork | undefined {
  return artworks.find(art => art.id === id);
}
